app:
    name: coo

server:
    port: 8082
    context-path: /coo
    session:
        timeout: 300
    tomcat:
        uri-encoding: UTF-8

spring:
    freemarker:
        suffix: .html
        templateEncoding: UTF-8
        templateLoaderPath: classpath:/views/
        content-type: text/html
    profiles:
        active: 'dev'
    #datasource:
        #jndi-name: jdbc/coo
        
mybatis:
    mapperLocations: classpath:mapper/*.xml
    
logging:
    level:
        com.hidm.coo.dao: debug