app:
    name: importexport

server:
    port: 8082
    context-path: /importexport
    session:
        timeout: 300
    tomcat:
        uri-encoding: UTF-8

spring:
    freemarker:
        suffix: .html
        templateEncoding: UTF-8
        templateLoaderPath: classpath:/views/
        content-type: text/html
    profiles:
        active: 'dev'
        
mybatis:
    mapperLocations: classpath:mapper/*.xml
    type-aliases-package: com.hidm.hrs.entity
    
logging:
    level:
        com.hidm.importexport.dao: info